In [2]:
import numpy as np
import scipy
from scipy import sparse


In [4]:
n=10
print([1]*n)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [6]:
for i in range(n):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [14]:
Y = np.array([5, 0, 6, 7, 8, 9, 2, 1, 4, 3])
matrix = sparse.coo_matrix(([1]*n, (Y, range(n))), shape = (10,n)).toarray()
print(matrix)

[[0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]]
