In [4]:
import numpy as np

In [5]:
x = np.array([[1, 0, 1], [1, 1, 1], [1, 1, -1], [-1, 1, 1]])
y = np.array([2, 2.7, -0.7, 2])
theta = np.array([0, 1, 2])

In [6]:
z = y - theta.dot(x.T)
print(z)

# Loss_h = np.ones_like(R_matrix) - R_matrix
# print(Loss_h)

# sum_loss = np.sum(Loss_h)/4
# print(sum_loss)

new_loss = (z**2)/2
print(new_loss)

new_sum_loss = np.sum(new_loss)/4
print(new_sum_loss)



[ 0.  -0.3  0.3 -1. ]
[0.    0.045 0.045 0.5  ]
0.1475


In [11]:
import scipy
from scipy.special import comb

In [12]:
deg1 = scipy.special.comb(150, 1)
deg2 = scipy.special.comb(151, 2)
deg3 = scipy.special.comb(152, 3)

result = deg1 + deg2 + deg3
print(result)

585275.0


In [13]:
x = np.array([1, 0, 0])
x_prime = np.array([0, 1, 0])

diff = x - x_prime

dist = np.linalg.norm(diff)
print(dist)

1.4142135623730951


In [16]:
from numpy import linalg

In [18]:
U0 = np.array([6, 0, 3, 6])
V0 = np.array([4, 2, 1])
X0 = np.outer(U0, V0)
print(X0)

[[24 12  6]
 [ 0  0  0]
 [12  6  3]
 [24 12  6]]


In [19]:
U0_2 = np.sum(U0**2)
V0_2 = np.sum(V0**2)

regul = (U0_2 + V0_2)/2
print(regul)

51.0
