In [1]:
import numpy as np


In [6]:
# def mean_vector(*arg):
#     sum_vec = np.array(arg)
#     for i in 1:length(arg):
#         sum_vec += *arg[i]
#     mean_vec = sum_vec / length(length(arg))
        
#     return mean_vec



In [35]:
X = np.array([[8, 4, 7], [2, 8, 1], [3, 1, 1], [9, 7, 4]])

mean_vec = np.mean(X, axis=0)
print(mean_vec)
mean_squared = np.outer(mean_vec.T, mean_vec)
print(mean_squared)


X_squared = np.zeros_like(mean_squared)
for i in range(X.shape[0]):
    X_squared += np.outer(X[i].T, X[i])

X_squared_mean = X_squared/X.shape[0]
print(X_squared_mean)


[5.5  5.   3.25]
[[30.25   27.5    17.875 ]
 [27.5    25.     16.25  ]
 [17.875  16.25   10.5625]]
[[39.5  28.5  24.25]
 [28.5  32.5  16.25]
 [24.25 16.25 16.75]]


In [36]:
result = X_squared_mean - mean_squared
print(result)

[[9.25   1.     6.375 ]
 [1.     7.5    0.    ]
 [6.375  0.     6.1875]]


In [39]:
cov=np.cov(X.T, bias=True) 
print(cov)

[[12.33333333  1.33333333  8.5       ]
 [ 1.33333333 10.          0.        ]
 [ 8.5         0.          8.25      ]]


In [49]:
X = np.array([2, -1, -2])

num_vec = (X.T).shape[0]

I_matrix = np.identity(num_vec)
one_by_one = np.ones_like(I_matrix)
one_by_one_reg = one_by_one/num_vec

H = I_matrix - one_by_one_reg
print(H)
print(X.T)

Hx = np.dot(H, X.T)
print(Hx)


[[ 0.66666667 -0.33333333 -0.33333333]
 [-0.33333333  0.66666667 -0.33333333]
 [-0.33333333 -0.33333333  0.66666667]]
[ 2 -1 -2]
[ 2.33333333 -0.66666667 -1.66666667]


In [51]:
H_2 = np.dot(H, H)
print(H_2)

H_2_x = np.dot(H_2, X)
print(H_2_x)

[[ 0.66666667 -0.33333333 -0.33333333]
 [-0.33333333  0.66666667 -0.33333333]
 [-0.33333333 -0.33333333  0.66666667]]
[ 2.33333333 -0.66666667 -1.66666667]


In [74]:
d = 2
u = np.array([1, 2]) * (1/np.sqrt(5))
# print(u)

X = np.array([[1, 2], [3, 4], [-1, 0]])

var_cal = []
for i in range(X.shape[0]):
    u_x = np.dot(u.T, X[i].T)
    print(u_x)
    var_cal.append(u_x)

    projection = u_x * u.T
    print(projection)

print(var_cal)
var_signed = np.var(var_cal)
print(var_signed)

2.23606797749979
[1. 2.]
4.919349550499537
[2.2 4.4]
-0.4472135954999579
[-0.2 -0.4]
[2.23606797749979, 4.919349550499537, -0.4472135954999579]
4.8


In [94]:
S = np.cov(X.T, bias = True)
print(S)

result_1 = np.dot(u, S)
print(result_1)
result_2 = np.dot(result_1, u.T)
print(result_2)

[[2.66666667 2.66666667]
 [2.66666667 2.66666667]]
[3.57770876 3.57770876]
4.799999999999999
