In [1]:
import numpy as np


In [2]:
# def mean_vector(*arg):
#     sum_vec = np.array(arg)
#     for i in 1:length(arg):
#         sum_vec += *arg[i]
#     mean_vec = sum_vec / length(length(arg))
        
#     return mean_vec



Principal Component Analysis (PCA)

In [3]:
X = np.array([[8, 4, 7], [2, 8, 1], [3, 1, 1], [9, 7, 4]])

mean_vec = np.mean(X, axis=0)
print(mean_vec)
mean_squared = np.outer(mean_vec.T, mean_vec)
print(mean_squared)


X_squared = np.zeros_like(mean_squared)
for i in range(X.shape[0]):
    X_squared += np.outer(X[i].T, X[i])

X_squared_mean = X_squared/X.shape[0]
print(X_squared_mean)


[5.5  5.   3.25]
[[30.25   27.5    17.875 ]
 [27.5    25.     16.25  ]
 [17.875  16.25   10.5625]]
[[39.5  28.5  24.25]
 [28.5  32.5  16.25]
 [24.25 16.25 16.75]]


In [4]:
result = X_squared_mean - mean_squared
print(result)

[[9.25   1.     6.375 ]
 [1.     7.5    0.    ]
 [6.375  0.     6.1875]]


In [5]:
cov=np.cov(X.T, bias=True) 
print(cov)

[[9.25   1.     6.375 ]
 [1.     7.5    0.    ]
 [6.375  0.     6.1875]]


In [6]:
X = np.array([2, -1, -2])

num_vec = (X.T).shape[0]

I_matrix = np.identity(num_vec)
one_by_one = np.ones_like(I_matrix)
one_by_one_reg = one_by_one/num_vec

H = I_matrix - one_by_one_reg
print(H)
print(X.T)

Hx = np.dot(H, X.T)
print(Hx)


[[ 0.66666667 -0.33333333 -0.33333333]
 [-0.33333333  0.66666667 -0.33333333]
 [-0.33333333 -0.33333333  0.66666667]]
[ 2 -1 -2]
[ 2.33333333 -0.66666667 -1.66666667]


In [7]:
H_2 = np.dot(H, H)
print(H_2)

H_2_x = np.dot(H_2, X)
print(H_2_x)

[[ 0.66666667 -0.33333333 -0.33333333]
 [-0.33333333  0.66666667 -0.33333333]
 [-0.33333333 -0.33333333  0.66666667]]
[ 2.33333333 -0.66666667 -1.66666667]


In [8]:
d = 2
u = np.array([1, 2]) * (1/np.sqrt(5))
# print(u)

X = np.array([[1, 2], [3, 4], [-1, 0]])

var_cal = []
for i in range(X.shape[0]):
    u_x = np.dot(u.T, X[i].T)
    print(u_x)
    var_cal.append(u_x)

    projection = u_x * u.T
    print(projection)

print(var_cal)
var_signed = np.var(var_cal)
print(var_signed)

2.23606797749979
[1. 2.]
4.919349550499537
[2.2 4.4]
-0.4472135954999579
[-0.2 -0.4]
[2.23606797749979, 4.919349550499537, -0.4472135954999579]
4.8


In [9]:
S = np.cov(X.T, bias = True)
print(S)

result_1 = np.dot(u, S)
print(result_1)
result_2 = np.dot(result_1, u.T)
print(result_2)

[[2.66666667 2.66666667]
 [2.66666667 2.66666667]]
[3.57770876 3.57770876]
4.799999999999999


In [10]:
A = np.array([1, 2, 3, 4])
B = np.array([2, 2, 2, 2])

multiple = A*B
print(multiple)

dot_product = np.dot(A, B)
print(dot_product)

mat_mul = A.T@B
print(mat_mul)

outer = np.outer(A, B)
print(outer)

[2 4 6 8]
20
20
[[2 2 2 2]
 [4 4 4 4]
 [6 6 6 6]
 [8 8 8 8]]


In [11]:
# X = np.array([[0, 1], [0, -1]])
# X = np.array([[1, 1/2], [-1, -1/2]])
# X = np.array([[0, 2], [1, -1], [-1, -1]])
X = np.array([[0, 2], [0, -2], [1, 1], [-1, -1]])


#Sample covariance matrix
cov_X = np.cov(X.T, bias = True) ## originally, we should put ddof=1 instead
print(cov_X)

[[0.5 0.5]
 [0.5 2.5]]


In [12]:
from numpy import linalg

w, v = linalg.eig(cov_X)
print(w, v)

[0.38196601 2.61803399] [[-0.97324899 -0.22975292]
 [ 0.22975292 -0.97324899]]


In [13]:
## unit vector of eivenvector
largest_idx_eivenvector = np.argmax(w)
print(largest_idx_eivenvector)

norm = linalg.norm(v[largest_idx_eivenvector])

reg_eigenvector = v[largest_idx_eivenvector]/norm

for i in range(X.shape[0]):
    y_1 = reg_eigenvector@X[0]
    y_2 = reg_eigenvector@X[1]
    y_3 = reg_eigenvector@X[2]

print(y_1, y_2, y_3)

array_y = np.array([y_1, y_2, y_3])
var_y = np.var(array_y)
print(var_y)

1
-1.9464979789354604 1.9464979789354604 -0.743496068920369
2.6487443445554533


Multi-dimensional scaling
MDS

In [14]:
X = np.array([1, 1, 1, -1, -1, 1])
X = X.reshape(3, 2)
print(X)

[[ 1  1]
 [ 1 -1]
 [-1  1]]


In [15]:
Gram_matrix = X.dot(X.T)
print(Gram_matrix)

cov_matrix = np.cov(X.T, bias=True)
print(cov_matrix)

[[ 2  0  0]
 [ 0  2 -2]
 [ 0 -2  2]]
[[ 0.88888889 -0.44444444]
 [-0.44444444  0.88888889]]


In [16]:
w, v = np.linalg.eig(Gram_matrix)
print(w, '\n', v)

[4.0000000e+00 4.4408921e-16 2.0000000e+00] 
 [[ 0.          0.          1.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]]


In [17]:
num_largest = np.argmax(w)
print(num_largest)
e_vector_largest = v.T[num_largest]
print(e_vector_largest)

0
[ 0.         -0.70710678  0.70710678]


In [18]:
projection_axis = e_vector_largest/np.linalg.norm(e_vector_largest)
print(projection_axis)

[ 0.         -0.70710678  0.70710678]


In [20]:
### Y = V1 * eigenvalues matrix

Stochastic Neighbor Embedding (SNE) and t-distributed Stochastic Neighbor Embedding (t-SNE)

In [22]:
A = 1
B = np.sqrt(2)

p12 = np.exp(-B**2)/(np.exp(-A**2) + np.exp(-B**2))
p13 = p12
p23 = np.exp(-A**2)/(np.exp(-A**2) + np.exp(-B**2))

# q12 = np.exp(-a^2)/(np.exp(-a^2) + np.exp(-(2*a)^2))
# q13 = q12
# q23 = np.exp(-(2*a)^2)/(np.exp(-a^2) + np.exp(-(2*a)^2))
print(p12, p13, p23)

KL = p12*np.log(p12/q12)

0.26894142136999505 0.26894142136999505 0.731058578630005
