In [2]:
import numpy as np
from numpy import linalg


Bayes Rule for Classification, Quadratic Discriminant Analysis (QDA) and Linear Discriminant Analysis (LDA)

In [3]:
X = np.array([1, 1, 1, -1])*(1/np.sqrt(2))
X = X.reshape(2, 2)
print(X)

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [4]:
### Linear Boundary
### ((mu_1^2-mu_0^2)/(2*sigma^2)+ln((1-p)/p))/(2*(mu_1-mu_0)/(2*sigma^2))

mu0 = np.array([0, 0])
mu1 = np.array([1, 0])

v_sig_squared = np.array([1, 1]) * (1/np.sqrt(2))
v_1 = np.array([1, -1]) * (1/np.sqrt(2))



In [19]:
V = np.array([1, 1, 1, -1])*(1/np.sqrt(2))
V = V.reshape(2, 2)
L = np.array([2, 0, 0, 1])
L = L.reshape(2, 2)

print(V, L)

P = V.dot(np.array([[1/np.sqrt(2), 0], [0, 1]]))

print(P)

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]] [[2 0]
 [0 1]]
[[ 0.5         0.70710678]
 [ 0.5        -0.70710678]]
