In [46]:
import networkx as nx
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import connected_components
import csv
import matplotlib.pyplot as plt
import networkx.algorithms.community as nx_comm

In [2]:
B = np.array([[0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
	[1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
	[1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
	[1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
	[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
	[0, 0, 0, 0, 1, 0, 1, 0, 1, 0]])

graph = csr_matrix(B)
#print(B)

n_components, labels = connected_components(csgraph=graph, directed=False, return_labels=True)
print(n_components)
print(labels)

G = nx.from_numpy_matrix(B)
# degree = nx.laplacian_matrix(G).toarray()
print(G.degree)


1
[0 0 0 0 0 0 0 0 0 0]
[(0, 3), (1, 4), (2, 1), (3, 5), (4, 3), (5, 2), (6, 1), (7, 1), (8, 3), (9, 3)]


In [3]:
B = np.array([[0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
	[1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
	[1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
	[1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
	[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
	[0, 0, 0, 0, 1, 0, 1, 0, 1, 0]])

new_B = B@B

for i in range(3, 1000):
    new_B = new_B@B
    # print('iteration:'+str(i))
    is_all_non_zero = np.all((new_B != 0))

    if is_all_non_zero:
        print('It\'s done with {} iterations.'.format(i))
        break
    # else:
        # print('There are zero(s) in the matrix.')


It's done with 4 iterations.


In [4]:
B = np.array([[0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
	[1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
	[1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
	[1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
	[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
	[0, 0, 0, 0, 1, 0, 1, 0, 1, 0]])

print(B@B@B@B@B)

[[46 59 14 62 30 40  5 21 38 25]
 [59 36 28 88 57 28 10 14 30 27]
 [14 28  2 14  6 17  2 10 19 10]
 [62 88 14 58 33 58 11 37 68 30]
 [30 57  6 33 24 32  9 20 47 32]
 [40 28 17 58 32 22  4 11 19 16]
 [ 5 10  2 11  9  4  2  2  9 13]
 [21 14 10 37 20 11  2  4  8 11]
 [38 30 19 68 47 19  9  8 26 33]
 [25 27 10 30 32 16 13 11 33 20]]


In [8]:
with open('release_directed_graph.txt', 'rb') as file:
    G = nx.DiGraph()
    graph_array = np.loadtxt(file)
    #print(graph_array)
    for i in range(graph_array.shape[0]):
        G.add_edge(graph_array[i][0], graph_array[i][1])
    
    print(G.degree)
    print(G.number_of_nodes())
    print(G.number_of_edges())
    # for row in graph_array: 
    #     edges = []
    #     a, b = row.strip().split()
    #     #print(a, b)
    #     int_a = int.from_bytes(a, byteorder='little')
    #     int_b = int.from_bytes(b, byteorder='big')
    #     edges.append(int_a)
    #     edges.append(int_b)
    #     print(edges)

    #     G.add_nodes_from(row)
    # print(G.degree)
    # print(G.number_of_nodes())
    # # print(G.number_of_edges())
    # G_edges = G.edges()
    # # print(len(G_edges))



[(0.0, 23), (3.0, 21), (10.0, 18), (12.0, 23), (25.0, 22), (39.0, 24), (50.0, 22), (74.0, 22), (76.0, 25), (84.0, 24), (87.0, 22), (89.0, 23), (96.0, 19), (1.0, 21), (4.0, 20), (13.0, 25), (29.0, 26), (31.0, 15), (33.0, 19), (35.0, 23), (82.0, 20), (2.0, 18), (38.0, 16), (42.0, 26), (44.0, 17), (49.0, 24), (66.0, 18), (73.0, 21), (75.0, 16), (93.0, 22), (17.0, 28), (24.0, 19), (30.0, 24), (53.0, 21), (71.0, 21), (94.0, 18), (21.0, 22), (37.0, 21), (46.0, 17), (58.0, 14), (60.0, 18), (79.0, 23), (81.0, 29), (97.0, 26), (5.0, 13), (6.0, 14), (62.0, 17), (80.0, 18), (7.0, 18), (41.0, 22), (51.0, 16), (77.0, 23), (88.0, 20), (8.0, 19), (34.0, 15), (59.0, 21), (61.0, 19), (63.0, 28), (67.0, 18), (9.0, 22), (27.0, 17), (45.0, 28), (48.0, 18), (52.0, 23), (65.0, 23), (86.0, 24), (83.0, 28), (99.0, 22), (11.0, 31), (19.0, 27), (36.0, 28), (54.0, 9), (56.0, 19), (90.0, 18), (98.0, 23), (28.0, 19), (26.0, 25), (40.0, 22), (14.0, 19), (20.0, 20), (55.0, 13), (57.0, 31), (70.0, 20), (78.0, 15), (9

In [12]:
# nx.draw(G)
# plt.show()

In [52]:
### Modularity

C = np.array([[0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
	[1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
	[1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
	[1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
	[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
	[0, 0, 0, 0, 1, 0, 1, 0, 1, 0]])

G1_even = nx.Graph()
G2_odd = nx.Graph()
G = nx.Graph()

C_odd = []
C_even = []
x_axis = int(C.shape[0]/2)
# print(type(x_axis))
# print(x_axis)
y_axis = int(C.shape[1]/2)

for i in range(C.shape[0]):
    if i%2 == 0:
        for j in range(C.shape[1]):
            if j%2 == 0:
                # np.append(C_even, C[i][j])
                C_even.append(C[i][j])
                # print(C_even)
C_even_mat = np.array([C_even])
C_even_mat = C_even_mat.reshape(x_axis, y_axis)

for i in range(C.shape[0]):
    if i%2 == 1:
        for j in range(C.shape[1]):
            if j%2 == 1:
                C_odd.append(C[i][j])
C_odd_mat = np.array([C_odd])
C_odd_mat = C_odd_mat.reshape(x_axis, y_axis)

# print(C_odd_mat)
# print(C_even_mat)


G1_even = nx.from_numpy_matrix(C_even_mat)
G2_odd = nx.from_numpy_matrix(C_odd_mat)
G = nx.from_numpy_matrix(C)




In [61]:
def modularity_partition(A, part):
	m = A.sum()/2
	ks = A.sum(axis=0)
	return ( A[part].T[part].T - ks[part][:,None]*ks[part][None,:]/(2*m) ).sum()/(2*m)

def modularity(A, parts):
	return sum([ modularity_partition(A, p) for p in parts ])

modularity(C, [[0,2,4,6,8], [1,3,5,7,9]])

-0.20414201183431957